const TARGETS = {
  agents: 'AGENTS.md',
  claude: 'CLAUDE.md',
  copilot: '.github/copilot-instructions.md',
  cursor: '.cursor/rules/project.mdc'
};

function list(items, fallback = 'None specified.') {
  return items?.length ? items.map((item) => `- ${item}`).join('\n') : fallback;
}

function normalize(spec = {}) {
  return {
    name: String(spec.name || 'Project'),
    summary: String(spec.summary || 'No project summary provided.'),
    stack: Array.isArray(spec.stack) ? spec.stack.map(String) : [],
    commands: typeof spec.commands === 'object' && spec.commands ? spec.commands : {},
    conventions: Array.isArray(spec.conventions) ? spec.conventions.map(String) : [],
    boundaries: Array.isArray(spec.boundaries) ? spec.boundaries.map(String) : [],
    verification: Array.isArray(spec.verification) ? spec.verification.map(String) : [],
    scope: String(spec.scope || '**/*')
  };
}

function body(raw) {
  const spec = normalize(raw);
  const commands = Object.entries(spec.commands).map(([name, command]) => `**${name}:** \`${command}\``);
  return `# ${spec.name} — agent instructions

## Project

${spec.summary}

## Stack

${list(spec.stack)}

## Commands

${list(commands)}

## Conventions

${list(spec.conventions)}

## Boundaries

${list(spec.boundaries)}

## Before finishing

${list(spec.verification)}
`;
}

function forTarget(spec, target) {
  const content = body(spec);
  if (target === 'cursor') {
    return `---\ndescription: Project-wide coding agent instructions\nglobs: ${normalize(spec).scope}\nalwaysApply: true\n---\n\n${content}`;
  }
  if (target === 'copilot') return `${content}\n<!-- Generated by RulePort. Edit ruleport.json, not this file. -->\n`;
  return `${content}\n<!-- Generated by RulePort from ruleport.json. -->\n`;
}

export function validateSpec(spec) {
  const errors = [];
  if (!spec || typeof spec !== 'object' || Array.isArray(spec)) errors.push('Policy must be a JSON object.');
  else {
    if (!String(spec.name ?? '').trim()) errors.push('name is required.');
    for (const field of ['stack', 'conventions', 'boundaries', 'verification']) {
      if (field in spec && !Array.isArray(spec[field])) errors.push(`${field} must be an array.`);
    }
    if ('commands' in spec && (!spec.commands || typeof spec.commands !== 'object' || Array.isArray(spec.commands))) errors.push('commands must be an object.');
  }
  return errors;
}

export function generateFiles(spec, requestedTargets = Object.keys(TARGETS)) {
  const errors = validateSpec(spec);
  if (errors.length) throw new Error(errors.join(' '));
  const unknown = requestedTargets.filter((target) => !(target in TARGETS));
  if (unknown.length) throw new Error(`Unknown targets: ${unknown.join(', ')}`);
  return Object.fromEntries(requestedTargets.map((target) => [TARGETS[target], forTarget(spec, target)]));
}

export { TARGETS };
